# Generated by Django 5.2.16 on 2026-07-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default=18, max_length=254),
            preserve_default=False,
        ),
    ]
